# Generated by Django 5.2 on 2025-05-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emp_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
