# Generated by Django 5.2 on 2025-05-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="emp_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.employee",
                to_field="emp_no",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
