# Generated by Django 5.2 on 2025-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_remove_customuser_emp_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='emp_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
