# Generated by Django 5.2 on 2025-05-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_employee_customuser_emp_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emp_no',
            field=models.ForeignKey(default='a001', on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', to_field='emp_no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='신짱구', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='과장', max_length=20),
            preserve_default=False,
        ),
    ]
