# Generated by Django 5.2 on 2025-05-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table3View",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("light", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("fan_status", models.CharField(max_length=10)),
                ("led_status", models.CharField(max_length=10)),
                ("timestamp", models.CharField(max_length=24)),
            ],
            options={
                "db_table": "table3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Table4",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("command", models.CharField(max_length=50)),
                ("start_time", models.CharField(max_length=24)),
                ("end_time", models.CharField(max_length=24)),
            ],
            options={
                "db_table": "table4",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Table5",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("command", models.CharField(max_length=50)),
                ("start_time", models.CharField(max_length=24)),
                ("end_time", models.CharField(max_length=24)),
            ],
            options={
                "db_table": "table5",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Table7",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("light", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("fan_status", models.CharField(max_length=10)),
                ("led_status", models.CharField(max_length=10)),
                ("timestamp", models.CharField(max_length=24)),
            ],
            options={
                "db_table": "table7",
                "managed": False,
            },
        ),
    ]
