# Generated by Django 5.2 on 2025-04-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("light", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("fan_status", models.CharField(max_length=10)),
                ("led_status", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sensor_data",
            },
        ),
    ]
