# Generated by Django 5.2 on 2025-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual_drive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "auto_dirve",
            },
        ),
    ]
